### ISSUE TITLE
The arxiv paper is acceppted by ICLR 2025?

### ISSUE THREAD

**Issue by StiphyJay** [YihangChen-ee/FCGS#1]
![image](https://github.com/user-attachments/assets/52e33696-379c-4b46-ad83-be559f93e988)

The arxiv paper is acceptted by ICLR 2025? 
The ICLR 2025 still in peer review process.

**Comment by YihangChen-ee** [comment]
Sorry, the correct arxiv version will be replaced in next announcement immediately
