### ISSUE TITLE
How to apply to GS algorithms with MLPs

### ISSUE THREAD

**Issue by LaFeuilleMorte** [YihangChen-ee/FCGS#3]
Hi, Thank you for this brilliant work. I'm working on Octree-gs, And I'm trying to use this for compressing. How can I do this?

**Comment by YihangChen-ee** [comment]
Unfortunately, FCGS is trained for the vanilla 3DGS format but not for Octree-gs.
If you want to compress Octree-gs using FCGS, you could retrain FCGS with a large Octree-gs dataset to make it able to directly compress them.

**Comment by gspeaky** [comment]
Would you be able to provide training scripts? It would make it easier to train it on specific GS repos and datasets

**Comment by YihangChen-ee** [comment]
Sorry, we do not plan to release the training scripts at this moment. You could refer to our paper to find the training strategies in the implementation details.
