### ISSUE TITLE
About GPU-based AC

### ISSUE THREAD

**Issue by ZhiyeTang** [YihangChen-ee/FCGS#4]
Nice work! The GPU-based AC significantly promotes the coding efficiency of arithmetic coding. However, according to the original code, only 16-bit symbols are compatible. How can I expand it to 32-bit symbols?

**Comment by YihangChen-ee** [comment]
Hi, thanks for your interest to our work. In most cases, 16-bit symbols are sufficient to express information. If you do want to expand it to 32 bits, you could modify the corresponding CUDA code to make it compatible with 32-bit symbols.[See here](https://github.com/YihangChen-ee/FCGS/tree/main/submodules/arithmetic)

**Comment by YihangChen-ee** [comment]
Hi, this code is modified from [torchac](https://github.com/fab-jul/torchac) implementation, and my understanding may not be fully precise. Maybe [torchac](https://github.com/fab-jul/torchac) or ChatGPT can give you better solutions.

**Comment by YihangChen-ee** [comment]
Hi,  I would like to recommend a document describing the implementation of the arithmetic coding approach: see this [link](https://staff.cs.utu.fi/kurssit/source_encoding_and_compression/spring_2016/SourceEncNotes.pdf). By search the key phrase `If the upper bound of`, you can locate the relevant places.

These magic numbers are used to divide the entire digit range into `1/4`, `2/4`, `3/4` segments.

This way, the codec can decide whether to append a `0`, append a `1`, expend the range, or just wait for the next symbol.
If you need to expand it to a 32-bit condition, you could also refer to theses `1/4`, `2/4`, `3/4` segments, at the digit range of 32 bits.
