### ISSUE TITLE
About arithmetic encoding

### ISSUE THREAD

**Issue by Yiozolm** [YihangChen-ee/FCGS#5]
I have no experience in CUDA C++ and one parameters real confuse me.
In **arithmetic_kernel.cu** line 197, you get the **out_cnt_all** in fuction **arithmetic_encode_cu** by 
`torch::Tensor out_cnt_all = torch::zeros({chunk_num}, torch::TensorOptions().dtype(torch::kInt32).device(sym.device()));`
For certain cdf, it can be regarded as a const. So why don't rerun metioned code again in **arithmetic_decode_cu** rather than be a parameter?
Can you explain more implementary details for me

**Comment by YihangChen-ee** [comment]
Hi, since we merge multiple sub-bitstreams from different CUDA threads into one bitstream, the variable **out_cnt_all** is used to record the length of each sub-bitstream such that these sub-bitstreams can be splitted during decoding accordingly. 

For your question `For certain cdf, it can be regarded as a const. So ... ?`, I could not fully understand, could you please explain it again?

**Comment by Yiozolm** [comment]
Until now, I can't fully understande how the `encode_arithmetic_kernel` works and I might mislead you lol.
In my view, **out_cnt_all** derives from **chunk_num** and **chunk_num** is computed by `const int chunk_num = (N + chunk_size - 1) / chunk_size`. The **chunk_size** is fixed for 10000 in python and **N** can be calculated from cdf. I wonder if the **out_cnt_all** is const, or it is change in operated `encode_arithmetic_kernel` ?
Thanks for your reply!

**Comment by YihangChen-ee** [comment]
**out_cnt_all** is not a const. **out_cnt_all** indicates the length of each sub-bitstream, which has different length. **out_cnt_all** is returned to the Python code, you could print it out to see its values.

I am afraid you mix the concept of _length of symbol string_ and _length of sub-bitstream_. _length of symbol string_ can be same, with a length of chunk_size for each. But _length of sub-bitstream_ is the length after coding this symbol string, which can have different length, depending on the accuracy of probability estimation.

**Comment by Yiozolm** [comment]
Thank you, I have got your mean
